### PR TITLE
Thermal Daemon configuration for IVI Platform

### PR DESCRIPTION
**Pull request by cyxlily**
Modified xml file to add configuration for ADL
IVI RVP i7-12700H and i5-12500H platform.

Tracked-On: OAM-109803

### CODE REVIEW

**Review by vilasrk — COMMENTED** [review]
In the commit message configuration added for IVI RVP i7-12700H and i5-12500H platform.
But i could see changes only for one platform.

**Comment by cyxlily** [comment]
> In the commit message configuration added for IVI RVP i7-12700H and i5-12500H platform. But i could see changes only for one platform.

Their product_name are both CIA1-PC 2

**Comment by Kunkka1988** [comment]
If we couldn't clarify the product name for ADL-I7 or ADL-I5, how about keep only one config for this platform?
Don't mention the CPU details in comments.

**Review by ljia5 — APPROVED** [review]

**Review by vilasrk — APPROVED** [review]
approving tentatively

**Review by lchen43 — APPROVED** [review]
LGTM

**Pull request merged**
