### PR TITLE
Calibrate thermal trip points for MTL platform.

### PR DESCRIPTION
**Pull request by RajaniRanjan**
Updated fine tuned temperature trip points and rapl power limits for Meteorlake platform.

Test Done -
Platform : MTL NUC

Tracked-On: OAM-126521

### CODE REVIEW

**Review by vilasrk — APPROVED** [review]
LGTM

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Comment by shyjumon-n** [comment]
@kaushlen Could you please add your comments too

**Review by vilasrk — APPROVED** [review]
LGTM

**Review by kaushlen — APPROVED** [review]

**Pull request merged**
